"""empty message

Revision ID: fe2a2bec292f
Revises: b0436b9f3d13
Create Date: 2023-03-27 21:59:53.143521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2a2bec292f'
down_revision = 'b0436b9f3d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1200), nullable=True),
    sa.Column('desc', sa.String(length=1200), nullable=True),
    sa.Column('owner', sa.String(length=1200), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('file', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
